version: 2.1

setup: true

orbs: 
  path-filtering: circleci/path-filtering@0.1.2

jobs:
  test:
    machine: true      
    steps:
      - checkout
      - run:
          name: Check docker version
          command: |
            docker --version
            docker-compose --version
            pwd
  after_parent_build:
    machine: true      
    steps:
      - checkout
      - run:
          name: Check docker version
          command: |
            docker --version

workflows:
  build_and_push_image:
    jobs:
      - test
      - path-filtering/filter:
          name: parent-build
          base-revision: circleci-project-setup
          config-path: .circleci/continue-config.yml
          mapping: |
            Nginx/.* build-parent true
#            Angular_example/.* build_child_1 true
#            App_example/.* build_child_2 true
#            React_app_example/.* build_child_3 true
          requires: 
            - test
      - after_parent_build
          requires: [parent-build]

