FROM node:12.20-alpine as build
WORKDIR /usr/src/app
#COPY package.json package-lock.json ./
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM 291602194426.dkr.ecr.us-west-1.amazonaws.com/nginx_parent:latest
COPY nginx.conf /etc/nginx/nginx.conf
#COPY --from=build /usr/src/app/dist/sample-app /usr/share/nginx/html
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
